version: "3.7"
services:
    app:
        build:
            args:
                user: mamel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravuecrud
        container_name: laravuecrud-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - laravuecrud

    db:
        image: mysql:8.0
        container_name: laravuecrud-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
#           - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        networks:
            - laravuecrud

    nginx:
        image: nginx:alpine
        container_name: laravuecrud-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravuecrud

    npm:
        image: node:latest
        volumes:
                - ./:/app
        working_dir: /app
        container_name: laravuecrud-npm
        networks:
            - laravuecrud
        ports:
            - 5173:5173
        command: bash -c "npm install && npm run dev"


networks:
    laravuecrud:
        driver: bridge
volumes:
    db_data:
